# Generated by Django 6.0.4 on 2026-04-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_alter_payout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
